export type {
  BggTag,
  SuggestedPlayerCount,
  OwnershipStatus,
  BggGameData,
  Game,
  AxisSource,
  Axis,
  DerivedFieldId,
  EmptyDerivedAxisConfiguration,
  PlayerCountFitConfiguration,
  PlayingTimeConfiguration,
  DerivedAxisConfigurationByField,
  AxisBase,
  PersonalAxis,
  TournamentAxis,
  DerivedAxisByField,
  DerivedAxis,
  DisabledLegacyAxis,
  EnabledAxis,
  Collection,
  FitnessBreakdownSource,
  FitnessBreakdownEntry,
  DerivedValueResolution,
  DerivedConfigurationPropertyDiscovery,
  FixedNativeScaleDiscovery,
  ConfigurationBoundNativeScaleDiscovery,
  NativeScaleDiscovery,
  DerivedAxisTemplateDiscovery,
  DerivedFieldDiscovery,
  DerivedFieldDiscoveryResponse,
  FitnessResult,
  AppConfig,
  TournamentSettings,
  SessionFilterType,
  SessionFilter,
  SessionStatus,
  TournamentSession,
  Comparison,
  CachedRecentComparison,
  TournamentGameStats,
  TournamentData,
  RecentComparison,
  TournamentGameStatsDisplay,
  GameWithScore,
  AddGameResult,
  BggSearchResult,
  ImportProgress,
  ImportComplete,
  PreferenceShape,
  ToleranceLevel,
  LeanDirection,
  VetoConfig,
  NativeScale,
  AxisDistribution,
  AxisWeightEntry,
  AttributeCluster,
  WeightRangeCluster,
  UtilityCurveDeclaration,
  DivergentGame,
  ComponentDistances,
  OutlierClassification,
  CollectionOutlier,
  AxisSuggestion,
  ProfileNarration,
  NarrationCacheState,
  CollectionProfile,
  ProfileData,
  PredictionConfidence,
  ReferenceGame,
  PredictionMeta,
  PredictionReadiness,
  PredictionSettings,
  PredictionUnavailable,
  PredictedGameResponse,
  NicheNeighbor,
  NicheEntry,
  NichePosition,
  NicheImpactEntry,
  NicheImpact,
  NicheTagFilter,
  NicheSettings,
  ComponentWeights,
  RedundancyNeighbor,
  RedundancyAdjustment,
  RedundancySettings,
  WishlistBreakdownEntry,
  WishlistEntry,
  BoxDimensions,
  Shelf,
  ShelfUnit,
  ShelfConfiguration,
  ShelfConfigMutationResult,
  ShelfUnitMutationResult,
  ShelfUnitRemovalResult,
  AssignedGame,
  ShelfAssignment,
  UnfittableEntry,
  OverflowEntry,
  AssignmentConflict,
  ShelfCapacityResult,
} from "./types";

export {
  CreateAxisSchema,
  UpdateAxisSchema,
  LegacyAxisRepairSchema,
  parseCreateAxisInput,
  parseUpdateAxisInput,
  parseLegacyAxisRepairInput,
  validateAxisForNativeScale,
  mergeAndValidateAxisUpdate,
  repairAndValidateLegacyAxis,
  CURRENT_COLLECTION_SCHEMA_VERSION,
  AxisSchema,
  GameSchema,
  CollectionSchema,
  RateGameSchema,
  AddGameSchema,
  SessionFilterSchema,
  StartSessionSchema,
  SubmitComparisonSchema,
  TournamentSettingsUpdateSchema,
  TournamentSettingsSchema,
  TournamentDataSchema,
  ShelfConfigurationSchema,
} from "./validation";

export {
  toErrorMessage,
  ValidationError,
  NotFoundError,
  AXIS_VALIDATION_CODES,
  CodedAxisValidationError,
} from "./errors";
export type { AxisValidationCode, AxisValidationDetail } from "./errors";

export { matchesBggTag, normalizeBggTagTokens } from "./bgg-tag-match";

export { resolveAxisValues } from "./axis-utils";

export {
  DERIVED_AXIS_REGISTRY,
  DerivedAxisPayloadSchema,
  createDerivedAxisFromPayload,
  createFreshCollectionDerivedAxes,
  validateDerivedAxisPayload,
  resolveDerivedAxisValue,
  getAxisNativeScale,
  getDerivedAxisNativeScale,
  isEnabledScoringAxis,
  isVectorEligibleAxis,
  summarizeDerivedAxisConfiguration,
  getDerivedFieldDiscovery,
  getDerivedSuggestionProjections,
} from "./derived-axis-registry";
export type {
  DerivedAxisRegistry,
  DerivedAxisTemplateDefaults,
  DerivedFieldDefinition,
  DerivedAxisPayload,
  DerivedAxisPayloadByField,
  DerivedAxisPayloadValidationResult,
  DerivedSuggestionAnalysis,
  DerivedSuggestionProjection,
} from "./derived-axis-registry";

export { resolveBaseDir, resolveSocketPath, resolveDataDir, resolveConfigPath } from "./paths";

export { RATING_LABELS, getRatingLabel } from "./rating-labels";

export {
  K_FLEXIBLE,
  K_MODERATE,
  K_STRICT,
  LEAN_GENTLE_MULTIPLIER,
  LEAN_STEEP_MULTIPLIER,
  calibrateTolerance,
  applyLean,
  getPreferenceCurveInvalidFields,
  isPreferenceCurveApplicable,
  applyPreferenceCurve,
} from "./curve-math";
export type { PreferenceCurveConfig } from "./curve-math";

export type {
  CreateAxisInput,
  CreateAxisOutput,
  UpdateAxisInput,
  UpdateAxisOutput,
  LegacyAxisRepairInput,
  LegacyAxisRepairOutput,
  RateGameInput,
  AddGameInput,
  SessionFilterInput,
  StartSessionInput,
  SubmitComparisonInput,
  TournamentSettingsUpdateInput,
} from "./validation";
